dist: xenial
language: node_js
node_js: '9'
sudo: required
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
before_script:
- ./node_modules/.bin/brunch build --production
- sed -i.orig 's/build/docs/g' karma.conf.js
after_success:
# Generate latest UserScript
- erb fateOfAllFools.prod.user.js.erb > docs/fateOfAllFools.user.js
# Configure Git
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git config credential.helper "store --file=.git/fate_credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/fate_credentials
- git remote add origin https://github.com/rslifka/fate_of_all_fools.git > /dev/null 2>&1
- git checkout master
# Commit releases so openuserjs can be notified
- cp public/fateOfAllFools.js docs/
- cp public/fateOfAllFools.css docs/
- git add docs/*
- git commit -m "[skip ci] Publishing build ${TRAVIS_BUILD_NUMBER}"
- git push
- echo "Done!"
