version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.15.0-browsers
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
