version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.2
  # https://circleci.com/developer/orbs/orb/circleci/browser-tools
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  build:
    docker:
      - image: cimg/node:16.15.0-browsers
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
