version: 2.1

orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.15.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build
      - run:
          command: npm run test
          name: Run Tests
      - run:
          command: node generateUserScript.js > ./docs/fateOfAllFools.user.js
          name: Generate new User Script

workflows:
  build_test:
    jobs:
      - build_and_test
