version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.2
  # https://circleci.com/developer/orbs/orb/circleci/browser-tools
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.15.0-browsers
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build
      - run:
          command: npm run test
          name: Run Tests

workflows:
  build_test:
    jobs:
      - build_and_test
